<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_GoodMarket
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */
/* @var $block \Magento\Catalog\Block\Adminhtml\Profile\Create */
?>
<div class="row">
    <div class="col-1" style="float: right">
        <a id="updatecategory" href="<?php echo $block->getUrl('goodmarket/config/fetchCategory');?>"><button">Update Category</button></a>
    </div>
</div>
<?php $gdcat = $block->getGoodMarketCategories(); ?>
<?php $category = $block->getCategories();  ?>
<?php $baseUrl = $block->getUrl('goodmarket/profile/savebymageid'); ?>
<?php /*echo '<pre>';print_r($category); exit; */?>
<?php if (count($gdcat) < 1) { ?>
    <span>Good Market Categories are not Fetched (File is missing). Please fetch token and then update categories.</span>
<?php } else { ?>
<div class='row'>
    <div class='col-1'>
        <h3>Magento Category</h3>
    </div>
    <div class='col-2'>
        <h3>Goodmarket Category</h3>
    </div>
</div>
    <?php foreach ($category as $catId => $catName) { ?>
        <?php
        $value = $block->checkCatId($catId);
        $value = substr($value, 2, -2);
        $ex = explode('","', $value);
        $value = implode(',', $ex);
        ?>
        <div class='row'>
            <form id='form-<?= $catId ?>'>
                <div class="col-1">
                    <select class='mgcat'>
                        <option value='<?= $catId ?>'><?= $catName ?></option>
                    </select>
                </div>
                <div class='col-2'>
                    <select class='gdcat' onchange='save(this, <?= $catId ?>)'>
                    <option value='0' selected>--Please Select--</option>
                        <?php foreach ($gdcat as $goodCat => $val) {?>
                            <?php $select = ''; ?>
                            <?php if ($value == $goodCat) {$select = 'selected';} ?>
                            <option value='<?= $goodCat ?>' <?= $select ?> > <?= $val ?></option>
                        <?php  } ?>
                    </select>
                </div>
            </form>
        </div>
    <?php } ?>
<script>
    function save(selectObject, categoryId) {
        var value = selectObject.value;
        var catId = categoryId;
        // console.log(value);
        // console.log(catId);
        // debugger;
        require([
            'jquery',
            'jquery/ui',
            'accordion',
            'lineProgressbar'
        ],
            function ($) {
                $.ajax({
                url: '<?= $baseUrl; ?>',
                type: 'POST',
                showLoader: true,
                data: {profileCategory: value, magentoCat: catId},
                success: function() {
                    console.log("Data sent!");
                }
            });
        }
        );
    }
</script>
<?php } ?>

<style>
     .row {
        width: 100%;
        display: inline-block;
         margin : 10px 0;
    }

    .col-1 {
        width: 28%;
        display: inline-block;
        margin: 5px;
        text-align: center;
    }

    .col-2 {
        display: inline-block;
        width: 50%;
        margin: 5px;
        text-align: center;
    }

    select.mgcat {
        width: 88%;
        text-align: center;
        margin: 5px;
        padding: 5px;
    }
    select.gdcat {
        padding: 5px;
        margin: 5px;
        text-align: center;
    }
     a#updatecategory {
         padding: 10px;
         background-color: #ff6225;
         font-size: 16px;
         font-weight: bold;
         color: #fff;
     }
     a#updatecategory:hover, a#updatecategory:visited {
         text-decoration: none;
         color: #fff;
     }
</style>
