<?php /* @var $block \Ced\GoodMarket\Block\Adminhtml\System\Config\Install */ ?>

<script>
    require([
        'jquery'
    ], function($) {
        function empty (e) {
            switch (e) {
                case "":
                case 0:
                case "0":
                case null:
                case false:
                    return true;
                default:
                    if (typeof e === "undefined") {
                        return true;
                    } else if (typeof e === "object" && Object.keys(e).length === 0){
                        return true;
                    } else {
                        return false;
                    }
            }
        }

        $('body').on('click', '#goodmarket-install', function () {
            var username = $('#goodmarket_settings_username').val();
            var vendorId = $('#goodmarket_settings_vendor_id').val();
            if (!empty(username) && !empty(vendorId)) {
                $.ajax({
                    showLoader: true, // enable loader
                    type: "POST",
                    url: "<?php echo $block->getAjaxUrl();?>",
                    data: {'username': username, 'vendorId': vendorId,'form_key': window.FORM_KEY},
                    success: function (response) {
                        if (response.hasOwnProperty('success') && response['success'] === true ) {
                            addMessage(response['message'], 'green');
                            if (response.hasOwnProperty('redirect_uri') && !empty(response['redirect_uri'])) {
                                window.open(response['redirect_uri'],'_blank');
                            }
                        } else {
                            addMessage(response['message'], 'red');
                        }
                          location.reload(true)
                    },
                    error: function () {
                        addMessage('Unable to connect.', 'red');
                    }

                });
            } else {
                addMessage('Kindly enter the credentials.', 'red');
            }

        });

        function addMessage(message, color) {
            var container = $('#goodmarket-install-message');
            if (container === undefined || container === null || container.length === 0) {
                $( "#goodmarket-install" ).before( "<span id='goodmarket-install-message'><span style='color: "+color+"; display: inline-block; max-width: 80%;'>"+message+"</span></span>" );
            } else {
                container.html('<span style="color: '+color+'; display: inline-block; max-width: 80%;">'+message+'</span>');
            }
        }
    });
</script>

<?php echo $block->getButtonHtml() ?>
