<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

?>
<?php /* @escapeNotVerified */ echo $block->getSomething();  ?>
<div id="<?= $block->getHtmlId() ?>" class="admin__grid-massaction">

    <?php if ($block->getHideFormElement() !== true):?>
    <form action="" id="<?= $block->getHtmlId() ?>-form" method="post">
        <?php endif ?>
        <div class="admin__grid-massaction-form">
            <?= $block->getBlockHtml('formkey')?>
            <select
                id="<?= $block->getHtmlId() ?>-select"
                class="required-entry local-validation admin__control-select"
                <?php /* @escapeNotVerified */ echo $block->getUiId('select') ?>>
                <option class="admin__control-select-placeholder" value="" selected><?php /* @escapeNotVerified */ echo __('Actions') ?></option>
                <?php foreach ($block->getItems() as $_item):?>
                    <option value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>"<?=($_item->getSelected() ? ' selected="selected"' : '')?>><?php /* @escapeNotVerified */ echo $_item->getLabel() ?></option>
                <?php endforeach; ?>
            </select>
            <span class="outer-span" id="<?= $block->getHtmlId() ?>-form-hiddens"></span>
            <span class="outer-span" id="<?= $block->getHtmlId() ?>-form-additional"></span>
            <?= $block->getApplyButtonHtml() ?>
        </div>
        <?php if ($block->getHideFormElement() !== true):?>
    </form>
<?php endif ?>
    <div class="no-display">
        <?php foreach ($block->getItems() as $_item): ?>
            <div id="<?= $block->getHtmlId() ?>-item-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-block">
                <?php if ('' != $_item->getBlockName()):?>
                    <?= $block->getChildHtml($_item->getBlockName());?>
                <?php endif;?>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="mass-select-wrap">
        <select
            id="<?= $block->getHtmlId() ?>-mass-select"
            class="action-select-multiselect _disabled"
            disabled="disabled"
            data-menu="grid-mass-select">
            <optgroup label="<?php /* @escapeNotVerified */ echo __('Mass Actions')?>">
                <option disabled selected></option>
                <?php if ($block->getUseSelectAll()):?>
                    <option value="selectAll">
                        <?php /* @escapeNotVerified */ echo __('Select All') ?>
                    </option>
                    <option value="unselectAll">
                        <?php /* @escapeNotVerified */ echo __('Unselect All') ?>
                    </option>
                <?php endif; ?>
                <option value="selectVisible">
                    <?php /* @escapeNotVerified */ echo __('Select Visible') ?>
                </option>
                <option value="unselectVisible">
                    <?php /* @escapeNotVerified */ echo __('Unselect Visible') ?>
                </option>
                <!--<option value="selectAllOnPage">
                    <?php /*/* @escapeNotVerified */ //echo __('Select All On Page') */?>
                </option>-->
            </optgroup>
        </select>
        <label for="<?= $block->getHtmlId() ?>-mass-select"></label>
    </div>

    <script>
        require(['jquery', 'domReady!'], function($){
            'use strict';
            $('#<?= $block->getHtmlId() ?>-mass-select')
                .removeClass('_disabled')
                .prop('disabled', false)
                .change(function () {
                    var massAction = $('option:selected', this).val();
                    this.blur();
                    switch (massAction) {
                    <?php if ($block->getUseSelectAll()):?>
                        case 'selectAll':
                            return <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.selectAll();
                            break;
                        case 'unselectAll':
                            return <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.unselectAll();
                            break;
                    <?php endif; ?>
                        case 'selectVisible':
                            return <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.selectVisible();
                            break;
                        case 'unselectVisible':
                            return <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.unselectVisible();
                            break;
                        case 'selectAllOnPage':
                            return <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.selectAllOnPage();
                            break;
                    }
                });
        });
        <?php if (!$block->getParentBlock()->canDisplayContainer()): ?>
        <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.setGridIds('<?php /* @escapeNotVerified */ echo $block->getGridIdsJson() ?>');
        <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.setGridIds('<?php /* @escapeNotVerified */  $block->getGridIdsJson() ?>');
        <?php endif; ?>
        function saveAndContinueEdit(urlTemplate,flag) {
            groupVendorPpcode_massaction = document.getElementById('groupVendorPpcode_massaction-form');
            if(groupVendorPpcode_massaction != null) {
                groupVendorPpcode_massaction.parentElement.removeChild(groupVendorPpcode_massaction);
                new Insertion.Bottom('edit_form',
                    groupVendorPpcode_massactionJsObject.fieldTemplate(
                        {name: 'in_profile',
                            value: groupVendorPpcode_massactionJsObject.checkedString}));
            }
            if(flag) {
                var editForm = jQuery('#edit_form');
                editForm.attr('action', urlTemplate);
                editForm.submit();
            }
        }
    </script>
</div>
