<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_GoodMarket
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
/**
 * @see Ced\GoodMarket\Block\Adminhtml\Config\FetchCategory
 */
?>
<script>
    require(['prototype'], function() {

        function validate() {
            var validationMessage = $('validation_category');
            new Ajax.Request('<?php  echo $block->escapeXssInUrl($block->getAjaxUrl()) ?>', {
                onSuccess: function(response) {
                    try {
                        if (response.responseText.isJSON()) {
                            if (response.responseText.evalJSON().msg == "success") {
                                var result = response.responseText.evalJSON().data;
                                validationMessage.removeClassName('hidden').addClassName('success')
                            } else if (response.responseText.evalJSON().msg == "error") {
                                var result = response.responseText.evalJSON().data;
                                validationMessage.removeClassName('hidden').addClassName('error')
                            }
                        }
                    } catch(e) {
                        validationMessage.removeClassName('hidden').addClassName('error')
                    }
                    validationMessage.update(result);
                }
            });
        }
        window.validate = validate;
//]]>
    });
</script>
<div class="actions actions-validate">
    <div id="validation_category" class="message-validation hidden"></div>
    <button onclick="validate(); return false;" class="action-validate" type="button" id="<?php echo $block->escapeHtml($block->getHtmlId()) ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
